name: Build & Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [21.x]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm install -g @vscode/vsce
      - run: npm run build --if-present
      - run: vsce package --pre-release --out vscode-supercollider-${{ github.ref_name }}.visx

      - uses: actions/upload-artifact@v4
        with:
          name: supercollider-vscode-${{ matrix.runs-on }}
          path: '*.visx'
          if-no-files-found: 'warn'